name: Build

on:
  [workflow_dispatch, push, pull_request]

env:
  BUILD_TYPE: Release
  
jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive
    
    - name: Build Plugin
      working-directory: ${{github.workspace}}/build
      env:
        CXX: clang++
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        cmake --build . --config $BUILD_TYPE -j4
        cpack

    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: neural_amp_modeler.lv2-linux-amd64
        path: ${{github.workspace}}/build/neural_amp_modeler.lv2

#    - name: Upload deb
#      uses: actions/upload-artifact@v1
#      with:
#        name: neural_amp_modeler.lv2-linux-deb-amd64
#        path: ${{github.workspace}}/build/*.deb
        
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: recursive
    
    - name: Build Plugin
      working-directory: ${{github.workspace}}/build
      run: |
        cmake.exe -G "Visual Studio 17 2022" -A x64  -T ClangCL ..
        cmake --build . --config=release -j4
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: neural_amp_modeler.lv2-win
        path: ${{github.workspace}}/build/neural_amp_modeler.lv2
